function info = sem_fieldfile_info( field_file_name )
% info = sem_read_fieldfile( field_file_name )
%
% Reads the contents of the field file generated by the SEM acoustics code, and
% returns some information about the field file.
%
% Takes 1 arguments:
%
%   field_file_name - String indicating the field file to read from disk.
%
% Returns 1 value:
%
%   info - Struct containing fields indicating n, mx, mz, the grid, and the number of time-steps.


    % Read the grid information and the grid.
    info.n  = h5read( field_file_name, '/grid/n' );
    info.mx = h5read( field_file_name, '/grid/mx' );
    info.my = h5read( field_file_name, '/grid/my' );
    info.mz = h5read( field_file_name, '/grid/mz' );
    info.x  = h5read( field_file_name, '/grid/x' );
    info.y  = h5read( field_file_name, '/grid/y' );
    info.z  = h5read( field_file_name, '/grid/z' );

    % Figure out how many time-steps are in the file.
    info.number_steps = h5read( field_file_name,'/field/number_steps' );

end
